### ISSUE TITLE
fastrtps1.5.0 participant discovery problem

### ISSUE THREAD

**Issue by Tony301X** [eProsima/Fast-RTPS#450] opened 2019-03-18 01:56 UTC
Software ENV: Ubuntu 16.04
fastrtps version: 1.5.0
Resource: source code
Hardware ENV: two hosts located in a LAN with IP address as, e.g., A(192.168.1.6), B(192.168.1.7)
Problem description:
   Case 1: When I run the simple talker/listener case, e.g., talker(publisher) on A, listener(subscriber) on B, it works well.
   Case 2: The case is more complex. On host A, start a participant which pub some topic, while on the same host A, there is two subscribers subscribing this topic. On B, start a participant which has a subscriber subscribing the same topic. The result is: the subscriber of the participant on host B is not discovered by participant on host A; but the two subscribers of host A have been discovered. In other words, when there is more subscribers with the same topic subscribed located on different hosts, the ones NOT located with same host as the publisher is not discovered correctly.

Any help is appropriated, thanks in advance!

**Comment by LuisGP** [comment] 2019-04-17 06:29
Hi @Tony301X 

I just tested with our HelloWorldExample and everything worked fine.

![image](https://user-images.githubusercontent.com/5285735/56265569-3340a880-60ea-11e9-8ee4-7b2191fe7d13.png)

As you can see, the upper pane is connected to a machine named **ubuntu59** while the rest of panes are local. I launched a subscriber in **ubuntu59** (like in your host B), and two subscribers and a publisher on my machine (acting as host A). 

Can you provide us more information to reproduce the issue like each instance configuration, the exact command used and the launching order?

Thank you very much.

**Comment by LuisGP** [comment] 2019-05-09 06:24
As we are unable to reproduce the issue and no more information was provided, I will close the issue.

**Closed by LuisGP** 2019-05-09 06:24 UTC
Labels: need more info
