### ISSUE TITLE
Ros package can't find fastcdr lib  if I download a new Fast-rtps 

### ISSUE THREAD

**Issue by faciler** [eProsima/Fast-RTPS#209] opened 2018-05-03 02:47 UTC
I have successfully call Fast-rtps lib in  ros package several months ago, but  I download the latest Fast-rtps,it doesn't work . error is undefined reference.Here attach my CmakeList file.
[CMakeLists.txt](https://github.com/eProsima/Fast-RTPS/files/1969508/CMakeLists.txt)

**Comment by johnmarkwayve** [comment] 2018-06-11 14:10
I'm having a similar issue, did you ever find a work-around?

**Comment by joseAndresGomezTovar** [comment] 2018-10-07 19:46
I was having the same issue however if you do this steps is fixed:
1- install git for windows (https://git-scm.com/download/win)... everything as default
2- open a new cmd <msbuild cmd>
3- go to FAST-RTPS folder
4- write cmake -G "Visual Studio 14 2015 Win64" -DTHIRDPARTY=ON -DPERFORMANCE_TESTS=ON

works fine for me

**Comment by LuisGP** [comment] 2019-05-09 05:29
Hi everyone,
We have never suffered this issue. It looks like you are trying to compile Fast-RTPS standalone instead of within the ROS2 build system. In that case, as @joseAndresGomezTovar wrote, you must set `-DTHIRDPARTY=ON` in cmake.
In any case, ROS2 now uses colcon to built, that manages directly this kind of dependencies, so the issue is obsolete and we are closing it.
Feel free to reopen it if you found troubles compiling Fast-RTPS with ROS2 using colcon.

**Closed by LuisGP** 2019-05-09 05:29 UTC
