### ISSUE TITLE
[bug] Publisher memroy will leak when close one of the subscribers

### ISSUE THREAD

**Issue by dfcknj** [eProsima/Fast-RTPS#141] opened 2017-09-04 13:31 UTC
I test HelloWorldExample  for one publisher and two subscribers,then close one of the subscribers,I found the publisher memory will increase.

use  vs2013 and win7

I modify the code like this:
switch(type)
    {
        case 1:
            {
                HelloWorldPublisher mypub;
                if(mypub.init())
                {
                    mypub.run(1000000);
                }
                break;
            }
        case 2:
            {
                HelloWorldSubscriber mysub;
                if(mysub.init())
                {
                    mysub.run();
                }
                break;
            }
    }

**Comment by MiguelCompany** [comment] 2018-06-26 07:07
I have tested with the [1.6.0](https://github.com/eProsima/Fast-RTPS/tree/v1.6.0) release using vs2013 on win10 and couldn't reproduce this. 

Could you try on your side?

**Comment by MiguelCompany** [comment] 2018-07-11 07:06
Closed as unreproducible

**Closed by MiguelCompany** 2018-07-11 07:06 UTC
