### ISSUE TITLE
[fastrtpsgen] ERROR: Getting platforms. null

### ISSUE THREAD

**Issue by OpusK** [eProsima/Fast-RTPS#248] opened 2018-08-30 02:55 UTC
Hi, 

Trying to use fastrtpsgen causes the following error:
```
$ fastrtpsgen LaserScan.idl 
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
ERROR: Getting platforms. null
```

The Install Manual says to use the recommended version, but I can not find it.

The JAVA version I am currently using is as follows. (Oracle JAVA JDK)
I tried with Oracle Java10, but I get the same error.
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

**Comment by MiguelCompany** [comment] 2018-09-04 05:49
Hi @OpusK 

* Which platform do you refer to? Linux? Windows? Mac?
* Are you using Fast-RTPS installer, or are you building from sources?
* If building from sources, which branch/tag are you building?

**Comment by OpusK** [comment] 2018-09-05 13:27
Hi, @MiguelCompany,

Sorry. I did not give you enough information.
The environment I have tested is shown below.

- OS : Linux(Ubuntu18.04)
- FastRTPS : building from source.
- Version : master branch
- JAVA : Oracle JAVA 8 JDK

**Comment by MiguelCompany** [comment] 2018-09-06 12:43
Hi @OpusK 

I couldn't reproduce the issue. 
I installed Oracle Java 8 jdk with `sudo apt install oracle-java8-set-default` and then followed FastRTPS instructions [here](https://eprosima-fast-rtps.readthedocs.io/en/latest/sources.html) adding `-DBUILD_JAVA=ON` and fastrtpsgen worked without problems

**Comment by MiguelCompany** [comment] 2018-09-07 06:39
Can you post the commands you are using to compile and attach its corresponding output?

**Comment by MiguelCompany** [comment] 2018-11-12 14:39
Hi @OpusK 

As we couldn't reproduce the problem and we had no answer for more than two months, we close this issue. Feel free to open it again if the problem persist on your side.

**Closed by MiguelCompany** 2018-11-12 14:39 UTC
Labels: need more info
