### ISSUE TITLE
Linux: No gateway set on any interface results in unreliable discovery [4098]

### ISSUE THREAD

**Issue by jespersmith** [eProsima/Fast-RTPS#167] opened 2017-12-13 00:28 UTC
I was running FastRTPS directly connected to an embedded system without a gateway set for any of its interfaces. This resulted in FastRTPS being unreliable in discovery and sending messages. Some topics were discovered (generally, ones that did not need fragmentation) and some were not. Switching to log level warning, I got a bunch of messages stating:

[RTPS_MSG_OUT Warning] Error: send_to: Network is unreachable
[RTPS_MSG_OUT Warning] Error: send_to: Invalid argument

**Comment by richiware** [comment] 2017-12-14 10:45
Are you using default values of ParticipantAttributes or are you changing some one, like metatrafficUnicastLocatorList and metatrafficMulticastLocatorList?

**Comment by john-east** [comment] 2018-04-03 16:10
I just ran into this same problem... I have a laptop running fastrtps on Ubuntu 16.04 x64 trying to talk to a nvidia tx2 running Ubuntu 16.04 arm, also using fastrtps. At first I thought it was something to do with the arm version but once I set the gateway on both computers to an actual gateway, the problem went away and they auto discover successfully.

This is using the default values of ParticipantAttributes.

**Comment by MiguelCompany** [comment] 2018-11-14 06:48
@jespersmith @john-east 
You can [disable multicast traffic](https://eprosima-fast-rtps.readthedocs.io/en/latest/pubsub.html#tips) and then [use initial peers](https://eprosima-fast-rtps.readthedocs.io/en/latest/pubsub.html#initial-peers) on one of the participants to indicate the location of the other participant.

**Comment by nate-jackson** [comment] 2019-02-08 19:28
we are seeing this even when trying to talk on localhost. On Ubuntu 16.04, with networking disabled, talker and listener do not work. On other dds implementations (coredx) we do get the two nodes talking, so it does seem specific to fastrtps.

**Comment by MiguelCompany** [comment] 2019-02-11 13:39
Hi @nate-jackson 
> on localhost, on Ubuntu 16.04, with networking disabled.
What does `networking disabled` exactly mean to you? Fast-RTPS needs at least the localhost interface to be up. I have checked the HelloWorldExample on Ubuntu 18.04.1 LTS having only the loopback interface enabled and it worked. It also works if I have the network interface up with the cable disconnected. Other dds implementations may use shared memory for localhost, so no network interface is required in that case.

Could you please explain your case deeper?

**Comment by nate-jackson** [comment] 2019-02-11 19:10
Thanks for the reply.

We are running on Ubuntu 16.04, in the networking dropdown there is a disable networking option. That's what networking disabled means.

We are using ros2, and I have a [corresponding ticket](https://discourse.ros.org/t/no-communication-if-no-gateway-is-set/2915/12) open there. I tried updating to a newer version of fastrtps and was able to see the issue go away when localhost is the only thing on the system. But unfortunately, that didn't fix the real issue we are having, which is that without a default gateway set, we can't get two machines to talk.

This is not always going to work for us, as we have some machines talking on multiple networks.

Here are my tests:
* Localhost
    1. With networking completely disabled, a talker and listener work on localhost.
    1. With networking enabled (but no default gateway), a talker and listener do not work on localhost.
    1. With networking enabled (with default gateway set, but nonexistent on the network), a talker and listener work on localhost.

* Two machines connected directly via ethernet cable
    1. With networking enabled (but no default gateway on either machine), a talker and listener do not work
    1. With networking enabled (default gateway configured on one machine, but not both), a talker and listener do not work
    1. With networking enabled (default gateway configured on both machines, but nonexistent on the network), a talker and listener work

**Comment by MiguelCompany** [comment] 2019-03-25 07:19
Hi @nate-jackson 

We tested all six cases using HelloWorld example with Fast-RTPS v1.7.2 and communication was successful in all cases. 

FYI, Fast-RTPS release v1.7.2 is going to be backported into ROS2 crystal for patch release 4. See [this comment](https://github.com/ros2/ros2/issues/669#issuecomment-474809818)

**Comment by nate-jackson** [comment] 2019-03-25 14:55
That's exciting! We'll be trying it out as soon as we can.

**Comment by LuisGP** [comment] 2019-04-17 06:40
Hi,
as @MiguelCompany indicated, in our testing, the issue is fixed. I'm closing this issue. If any of you found there is still problems or need more information feel free to reopen it.

**Closed by LuisGP** 2019-04-17 06:40 UTC
