### ISSUE TITLE
Open Splice / Fast RTPS interoperability issue [4766]

### ISSUE THREAD

**Issue by Kildeor** [eProsima/Fast-RTPS#407] opened 2019-02-11 14:49 UTC
Hi,

I want to establish the communication between a data producer with OpenSplice 6.5 (RTPS protocol 2.1) and a data consumer with Fast-RTPS 1.5. I get the following errors on OpenSplice:

- recv:  malformed packet received from vendor 1.15 state parse:acknack <52545053 0201010f 28380f01 00000d5c 00000002 0e010c00 7bf6db0a 000000c4 @0x24 06011800 c7000200 c2000200 00000000 00000000 00000000 01000000> (note: maybe partially bswap'd) {{6,1,24},200c7,200c2,0,0}

- tev: ddsi_udp_conn_write failed with error code 101ddsi_conn_write failed -1

I tried with several versions of Fast-RTPS but without success. Is there a version of Fast-RTPS compatible with this producer ? or a solution to solve these errors ?

Thanks

**Comment by MiguelCompany** [comment] 2019-02-26 11:10
I haven't been able to reproduce this, but I have checked with OpenSplice 6.9 instead of 6.5. It seems to be complaining on what an `acknack` message with a base value of 0. This is what is usually called a `Preemptive ACKNACK`, which is used to force the writer to send a heartbeat. All vendors we are aware of accept this kind of messages, and I OpenSplice 6.9 certainly does.

**Comment by MiguelCompany** [comment] 2019-03-11 11:32
I am closing this, as it couldn't be reproduced. Feel free to reopen if still an issue.

**Closed by MiguelCompany** 2019-03-11 11:32 UTC

**Comment by Kildeor** [comment] 2019-03-19 15:01
Sorry for the delay and thanks for watching my problem. I managed to establish communication in the simplest cases. The hardware that provides the DDS data must have a problem. I am currently on an alternative solution. I will publish this thread if I find more information.
