### ISSUE TITLE
How can I run Quick Demo? [6222]

### ISSUE THREAD

**Issue by jtrimind** [eProsima/Fast-RTPS#673] opened 2019-08-23 06:29 UTC
The readme.md is written like below.

`Then, download the docker image file from https://eprosima.com/index.php/downloads-all`

Although I access the link and fill the form, I can't find `ubuntu-fast-rtps.tar`

Where can I download it?

**Comment by LuisGP** [comment] 2019-10-02 09:37
Closing, duplicate of #642

**Closed by LuisGP** 2019-10-02 09:37 UTC
Labels: duplicate
